/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.logowanierejestracja;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Arrays;
import javax.swing.JOptionPane;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Scanner;

//Email
import java.util.regex.Matcher;
import java.util.regex.Pattern;


/**
 *
 * @author Michał
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        addKeyListenerTo_md_jTextFieldUsername();
        addKeyListernerTo_md_jPasswordField();
        addToolTipText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        md_jPanelRejestracja = new javax.swing.JPanel();
        md_jLabelRejestracja = new javax.swing.JLabel();
        md_jLabelUsername = new javax.swing.JLabel();
        md_jTextFieldUsername = new javax.swing.JTextField();
        md_jLabelEmailRejestracja = new javax.swing.JLabel();
        md_jTextFieldEmailRejestracja = new javax.swing.JTextField();
        md_jLabelPasswordRejestracja = new javax.swing.JLabel();
        md_jPasswordFieldRejestracja = new javax.swing.JPasswordField();
        md_jLabelCorfimPassword = new javax.swing.JLabel();
        md_jConfirmPasswordField = new javax.swing.JPasswordField();
        md_jButtonRejestracja = new javax.swing.JButton();
        md_jPanelLogowanie = new javax.swing.JPanel();
        md_jLabelLogowanie = new javax.swing.JLabel();
        md_jLabelEmail = new javax.swing.JLabel();
        md_jTextFieldEmail = new javax.swing.JTextField();
        md_jLabelPassword = new javax.swing.JLabel();
        md_jPasswordField = new javax.swing.JPasswordField();
        md_jButtonZaloguj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        md_jLabelRejestracja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        md_jLabelRejestracja.setText("Rejestracja");

        md_jLabelUsername.setText("Username");

        md_jLabelEmailRejestracja.setText("Email");

        md_jLabelPasswordRejestracja.setText("Password");

        md_jLabelCorfimPassword.setText("Confirm Password");

        md_jButtonRejestracja.setText("Rejestracja");
        md_jButtonRejestracja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jButtonRejestracjaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout md_jPanelRejestracjaLayout = new javax.swing.GroupLayout(md_jPanelRejestracja);
        md_jPanelRejestracja.setLayout(md_jPanelRejestracjaLayout);
        md_jPanelRejestracjaLayout.setHorizontalGroup(
            md_jPanelRejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(md_jPanelRejestracjaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(md_jPanelRejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(md_jTextFieldUsername)
                    .addComponent(md_jTextFieldEmailRejestracja)
                    .addComponent(md_jPasswordFieldRejestracja)
                    .addComponent(md_jConfirmPasswordField)
                    .addGroup(md_jPanelRejestracjaLayout.createSequentialGroup()
                        .addGroup(md_jPanelRejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(md_jLabelRejestracja)
                            .addComponent(md_jLabelUsername)
                            .addComponent(md_jLabelEmailRejestracja)
                            .addComponent(md_jLabelPasswordRejestracja)
                            .addComponent(md_jLabelCorfimPassword)
                            .addComponent(md_jButtonRejestracja))
                        .addGap(0, 221, Short.MAX_VALUE)))
                .addContainerGap())
        );
        md_jPanelRejestracjaLayout.setVerticalGroup(
            md_jPanelRejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(md_jPanelRejestracjaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(md_jLabelRejestracja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(md_jLabelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(md_jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(md_jLabelEmailRejestracja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(md_jTextFieldEmailRejestracja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(md_jLabelPasswordRejestracja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(md_jPasswordFieldRejestracja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(md_jLabelCorfimPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(md_jConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(md_jButtonRejestracja)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Rejestracja", md_jPanelRejestracja);

        md_jLabelLogowanie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        md_jLabelLogowanie.setText("Logowanie");

        md_jLabelEmail.setText("Email");

        md_jLabelPassword.setText("Password");

        md_jButtonZaloguj.setText("Zaloguj");
        md_jButtonZaloguj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jButtonZalogujActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout md_jPanelLogowanieLayout = new javax.swing.GroupLayout(md_jPanelLogowanie);
        md_jPanelLogowanie.setLayout(md_jPanelLogowanieLayout);
        md_jPanelLogowanieLayout.setHorizontalGroup(
            md_jPanelLogowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(md_jPanelLogowanieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(md_jPanelLogowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(md_jPanelLogowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(md_jLabelLogowanie)
                        .addComponent(md_jLabelEmail)
                        .addComponent(md_jTextFieldEmail)
                        .addComponent(md_jLabelPassword)
                        .addComponent(md_jPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))
                    .addComponent(md_jButtonZaloguj))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        md_jPanelLogowanieLayout.setVerticalGroup(
            md_jPanelLogowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(md_jPanelLogowanieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(md_jLabelLogowanie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(md_jLabelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(md_jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(md_jLabelPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(md_jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(md_jButtonZaloguj)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Logowanie", md_jPanelLogowanie);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Utworzenie zmiennych
    public String username = "";
    public String email = "";
    public int sprawdzanie = 0;
    
    //Rejestracja
    private void md_jButtonRejestracjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jButtonRejestracjaActionPerformed
        //Sprawdzanie czy dane są prawidłowe
        if (md_jTextFieldUsername.getText().length() > 20 || md_jTextFieldUsername.getText().length() < 2){
            JOptionPane.showMessageDialog(null, "Pole username jest źle wypełnione!");
            sprawdzanie += 1;
        }
        String password = String.valueOf(md_jPasswordFieldRejestracja.getPassword());
        System.out.println(password);
        if (!Arrays.equals(md_jPasswordFieldRejestracja.getPassword(), md_jConfirmPasswordField.getPassword())){
            JOptionPane.showMessageDialog(null, "Hasla nie sa takie same");
            sprawdzanie += 1;
        }else{
            System.out.println("Hasla sa takie same");
        }
        char [] passChar = md_jPasswordFieldRejestracja.getPassword();
        
        if (passChar.length < 4){
            JOptionPane.showMessageDialog(null, "W hasle jest za malo liter");
            sprawdzanie += 1;
        }   
        
        //Pobieranie danych do zmiennych
        username = md_jTextFieldUsername.getText();
        email = md_jTextFieldEmailRejestracja.getText();
        String zapis = username+";"+email+";"+password;
        //String zapisDoLogowania = email+";"+password;
        System.out.println(zapis);
        
        //Walidacja Email
        Pattern pat = Pattern.compile(".+@.+\\.[a-z]+");
        Matcher match = pat.matcher(email);
        
        boolean matchFound = match.matches();
        
        if (matchFound == true){
            System.out.println("Poprawny email");
        }else{
            JOptionPane.showMessageDialog(null, "Podany adres email nie jest prawidłowy");
            sprawdzanie += 1;
        }
        
        //Czyszczenie pól
        md_jTextFieldEmailRejestracja.setText("");
        md_jTextFieldUsername.setText("");
        md_jPasswordFieldRejestracja.setText("");
        md_jConfirmPasswordField.setText("");
        
        //Próba zapisu do pliku
        if(sprawdzanie == 0){
            try {
                FileWriter fw = new FileWriter(plik, true);
                fw.write(zapis+"\n");
                fw.close();
            } catch (IOException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            sprawdzanie = 0;
        }
    }//GEN-LAST:event_md_jButtonRejestracjaActionPerformed
    
    //Utworzenie zmiennych do systemu logownania
    public String emailLogowanie = "";
    public String hasloLogowanie = "";
    
    //Logowanie
    private void md_jButtonZalogujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jButtonZalogujActionPerformed
        //Przeniesienie do funkcji typu String
        readFromFile();
    }//GEN-LAST:event_md_jButtonZalogujActionPerformed
    //Funkcja odpowiadająca za odczyt z pliku i sprawdzanie danych potrzebnych do logowania
    public String readFromFile(){
        //Pobieranie danych z pól do zmiennych
        hasloLogowanie = String.valueOf(md_jPasswordField.getPassword());
        emailLogowanie = md_jTextFieldEmail.getText();
        
        //Przygotowanie zmiennych w odpowiednim formacie do zapisu
        String daneLogowanie = emailLogowanie+";"+hasloLogowanie;
        System.out.println(daneLogowanie);
        
        String message = "";
        
        //Próba zapisu do pliku
        Scanner sc;
        try {
            sc = new Scanner(new File(plik));
            while (sc.hasNext()){
            String aktualnaLinia = sc.nextLine();
            String[] parts = aktualnaLinia.split(";");
            String username = parts[0];
            String email = parts[1];
            String password = parts[2];
            
            String help1 = email+";"+password;
            System.out.println("Help1 = "+help1);
            System.out.println(aktualnaLinia);
            
                if (daneLogowanie.equals(help1)){
                    JOptionPane.showMessageDialog(null, "Udało ci się zalogować! Witaj: "+username);
                }else{
                    JOptionPane.showMessageDialog(null, "Nie udało ci się zalogować!");
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        return message;
    }
    
    //KeyListrenery
    private void addKeyListenerTo_md_jTextFieldUsername(){
        md_jTextFieldUsername.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                char znak = e.getKeyChar();
                int kod = (int)znak;                
                
                if (kod >= 97 && kod <= 199 || kod >= 65 && kod <= 89 || znak == KeyEvent.VK_BACK_SPACE){
                    md_jTextFieldUsername.setEditable(true);
                }
                else{
                    md_jTextFieldUsername.setEditable(false);
                }
            }

            @Override
            public void keyPressed(KeyEvent e) {

            }

            @Override
            public void keyReleased(KeyEvent e) {

            }
        });
    }
    
    private void addKeyListernerTo_md_jPasswordField(){
        md_jPasswordFieldRejestracja.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
               char znak = e.getKeyChar();
               int kod = (int) znak;
               
               if (kod >= 97 && kod <= 199 || kod >= 65 && kod <= 89 || znak == KeyEvent.VK_BACK_SPACE || znak >= '0' && znak <= '9'){
                   md_jPasswordFieldRejestracja.setEditable(true);
               } else{
                   md_jPasswordFieldRejestracja.setEditable(false);
               }
            }

            @Override
            public void keyPressed(KeyEvent e) {
                
            }

            @Override
            public void keyReleased(KeyEvent e) {
                
            }
        });
    }
    
    //Dodawanie podpowiedzi do pól
    private void addToolTipText(){
        md_jTextFieldUsername.setToolTipText("Pole username musi mieć od 2 do 20 znaków i zawierać tylko litery");
        md_jPasswordFieldRejestracja.setToolTipText("Pole haslo musi mieć conajmniej 4 znaki, można wpisać tylko liczby i litery");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    //Tworzenie plików
    public String plik = "sekretnehasla.csv";
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton md_jButtonRejestracja;
    private javax.swing.JButton md_jButtonZaloguj;
    private javax.swing.JPasswordField md_jConfirmPasswordField;
    private javax.swing.JLabel md_jLabelCorfimPassword;
    private javax.swing.JLabel md_jLabelEmail;
    private javax.swing.JLabel md_jLabelEmailRejestracja;
    private javax.swing.JLabel md_jLabelLogowanie;
    private javax.swing.JLabel md_jLabelPassword;
    private javax.swing.JLabel md_jLabelPasswordRejestracja;
    private javax.swing.JLabel md_jLabelRejestracja;
    private javax.swing.JLabel md_jLabelUsername;
    private javax.swing.JPanel md_jPanelLogowanie;
    private javax.swing.JPanel md_jPanelRejestracja;
    private javax.swing.JPasswordField md_jPasswordField;
    private javax.swing.JPasswordField md_jPasswordFieldRejestracja;
    private javax.swing.JTextField md_jTextFieldEmail;
    private javax.swing.JTextField md_jTextFieldEmailRejestracja;
    private javax.swing.JTextField md_jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
