/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.przelicznikjednostek;

import java.io.BufferedWriter;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import static java.lang.System.in;
import javax.swing.JFileChooser;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Michał
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        md_jPanelMain = new javax.swing.JPanel();
        md_jTabbedPaneMain = new javax.swing.JTabbedPane();
        md_jPanelOdleglosci = new javax.swing.JPanel();
        md_jLabelPodajOdleglosc = new javax.swing.JLabel();
        md_jButtonKM = new javax.swing.JButton();
        md_jSpinnerOdleglosc = new javax.swing.JSpinner();
        md_jLabelPrzeliczNa = new javax.swing.JLabel();
        md_jButtonPrzeliczNaM = new javax.swing.JButton();
        md_jLabelWynik = new javax.swing.JLabel();
        md_jButtonM = new javax.swing.JButton();
        md_jButtonPrzeliczNaKM = new javax.swing.JButton();
        md_jButtonOblicz = new javax.swing.JButton();
        md_jButtonPrzeliczNaCM = new javax.swing.JButton();
        md_jLabelWynikTekst = new javax.swing.JLabel();
        md_jButtonCM = new javax.swing.JButton();
        md_jPanelTemperatura = new javax.swing.JPanel();
        md_jLabelPodajTemp = new javax.swing.JLabel();
        md_jButtonK = new javax.swing.JButton();
        md_jSpinnerTemp = new javax.swing.JSpinner();
        md_jLabelPrzeliczNa1 = new javax.swing.JLabel();
        md_jButtonPrzeliczNaf = new javax.swing.JButton();
        md_jLabelWynikTemp = new javax.swing.JLabel();
        md_jButtonF = new javax.swing.JButton();
        md_jButtonPrzeliczNaK = new javax.swing.JButton();
        md_jButtonObliczTemp = new javax.swing.JButton();
        md_jButtonPrzeliczNaC = new javax.swing.JButton();
        md_jLabelWynikTekst1 = new javax.swing.JLabel();
        md_jButtonC = new javax.swing.JButton();
        md_jMenuBarMain = new javax.swing.JMenuBar();
        md_jMenuPlik = new javax.swing.JMenu();
        md_jMenuItemPokazHistorie = new javax.swing.JMenuItem();
        md_jMenuItemZamknij = new javax.swing.JMenuItem();
        md_jMenuOProgramie = new javax.swing.JMenu();
        md_jMenuItemOProgramie = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        md_jPanelMain.setBackground(new java.awt.Color(153, 153, 153));

        md_jTabbedPaneMain.setBackground(new java.awt.Color(255, 255, 255));

        md_jPanelOdleglosci.setBackground(new java.awt.Color(102, 102, 102));

        md_jLabelPodajOdleglosc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        md_jLabelPodajOdleglosc.setForeground(new java.awt.Color(255, 255, 255));
        md_jLabelPodajOdleglosc.setText("Podaj odległość: ");

        md_jButtonKM.setText("km");
        md_jButtonKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jButtonKMActionPerformed(evt);
            }
        });

        md_jLabelPrzeliczNa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        md_jLabelPrzeliczNa.setForeground(new java.awt.Color(255, 255, 255));
        md_jLabelPrzeliczNa.setText("Przelicz na: ");

        md_jButtonPrzeliczNaM.setText("m");
        md_jButtonPrzeliczNaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jButtonPrzeliczNaMActionPerformed(evt);
            }
        });

        md_jLabelWynik.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        md_jLabelWynik.setForeground(new java.awt.Color(255, 255, 255));
        md_jLabelWynik.setText("0");

        md_jButtonM.setText("m");
        md_jButtonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jButtonMActionPerformed(evt);
            }
        });

        md_jButtonPrzeliczNaKM.setText("km");
        md_jButtonPrzeliczNaKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jButtonPrzeliczNaKMActionPerformed(evt);
            }
        });

        md_jButtonOblicz.setText("Oblicz");
        md_jButtonOblicz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jButtonObliczActionPerformed(evt);
            }
        });

        md_jButtonPrzeliczNaCM.setText("cm");
        md_jButtonPrzeliczNaCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jButtonPrzeliczNaCMActionPerformed(evt);
            }
        });

        md_jLabelWynikTekst.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        md_jLabelWynikTekst.setForeground(new java.awt.Color(255, 255, 255));
        md_jLabelWynikTekst.setText("Wynik: ");

        md_jButtonCM.setText("cm");
        md_jButtonCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jButtonCMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout md_jPanelOdleglosciLayout = new javax.swing.GroupLayout(md_jPanelOdleglosci);
        md_jPanelOdleglosci.setLayout(md_jPanelOdleglosciLayout);
        md_jPanelOdleglosciLayout.setHorizontalGroup(
            md_jPanelOdleglosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(md_jPanelOdleglosciLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(md_jPanelOdleglosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(md_jLabelPodajOdleglosc)
                    .addComponent(md_jLabelPrzeliczNa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(md_jPanelOdleglosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(md_jPanelOdleglosciLayout.createSequentialGroup()
                        .addComponent(md_jButtonPrzeliczNaCM)
                        .addGap(18, 18, 18)
                        .addComponent(md_jButtonPrzeliczNaM, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(md_jSpinnerOdleglosc))
                .addGroup(md_jPanelOdleglosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(md_jPanelOdleglosciLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(md_jButtonPrzeliczNaKM))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, md_jPanelOdleglosciLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(md_jButtonCM, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(md_jButtonM, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(md_jButtonKM)
                .addGap(30, 30, 30)
                .addGroup(md_jPanelOdleglosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(md_jPanelOdleglosciLayout.createSequentialGroup()
                        .addComponent(md_jLabelWynikTekst)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(md_jLabelWynik, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                    .addComponent(md_jButtonOblicz, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        md_jPanelOdleglosciLayout.setVerticalGroup(
            md_jPanelOdleglosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(md_jPanelOdleglosciLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(md_jPanelOdleglosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(md_jLabelPodajOdleglosc)
                    .addComponent(md_jButtonCM)
                    .addComponent(md_jButtonM)
                    .addComponent(md_jButtonKM)
                    .addComponent(md_jButtonOblicz)
                    .addComponent(md_jSpinnerOdleglosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(md_jPanelOdleglosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(md_jLabelPrzeliczNa)
                    .addComponent(md_jButtonPrzeliczNaCM)
                    .addComponent(md_jButtonPrzeliczNaM)
                    .addComponent(md_jButtonPrzeliczNaKM)
                    .addComponent(md_jLabelWynik)
                    .addComponent(md_jLabelWynikTekst))
                .addContainerGap(354, Short.MAX_VALUE))
        );

        md_jLabelPodajOdleglosc.getAccessibleContext().setAccessibleName("Podaj odległość w metrach: ");

        md_jTabbedPaneMain.addTab("Odległości", md_jPanelOdleglosci);

        md_jPanelTemperatura.setBackground(new java.awt.Color(102, 102, 102));

        md_jLabelPodajTemp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        md_jLabelPodajTemp.setForeground(new java.awt.Color(255, 255, 255));
        md_jLabelPodajTemp.setText("Podaj temperature: ");

        md_jButtonK.setText("k");
        md_jButtonK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jButtonKActionPerformed(evt);
            }
        });

        md_jLabelPrzeliczNa1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        md_jLabelPrzeliczNa1.setForeground(new java.awt.Color(255, 255, 255));
        md_jLabelPrzeliczNa1.setText("Przelicz na: ");

        md_jButtonPrzeliczNaf.setText("f");
        md_jButtonPrzeliczNaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jButtonPrzeliczNafActionPerformed(evt);
            }
        });

        md_jLabelWynikTemp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        md_jLabelWynikTemp.setForeground(new java.awt.Color(255, 255, 255));
        md_jLabelWynikTemp.setText("0");

        md_jButtonF.setText("f");
        md_jButtonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jButtonFActionPerformed(evt);
            }
        });

        md_jButtonPrzeliczNaK.setText("k");
        md_jButtonPrzeliczNaK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jButtonPrzeliczNaKActionPerformed(evt);
            }
        });

        md_jButtonObliczTemp.setText("Oblicz");
        md_jButtonObliczTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jButtonObliczTempActionPerformed(evt);
            }
        });

        md_jButtonPrzeliczNaC.setText("c");
        md_jButtonPrzeliczNaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jButtonPrzeliczNaCActionPerformed(evt);
            }
        });

        md_jLabelWynikTekst1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        md_jLabelWynikTekst1.setForeground(new java.awt.Color(255, 255, 255));
        md_jLabelWynikTekst1.setText("Wynik: ");

        md_jButtonC.setText("c");
        md_jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jButtonCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout md_jPanelTemperaturaLayout = new javax.swing.GroupLayout(md_jPanelTemperatura);
        md_jPanelTemperatura.setLayout(md_jPanelTemperaturaLayout);
        md_jPanelTemperaturaLayout.setHorizontalGroup(
            md_jPanelTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(md_jPanelTemperaturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(md_jPanelTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(md_jLabelPodajTemp)
                    .addComponent(md_jLabelPrzeliczNa1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(md_jPanelTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(md_jPanelTemperaturaLayout.createSequentialGroup()
                        .addComponent(md_jButtonPrzeliczNaC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(md_jButtonPrzeliczNaf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(md_jSpinnerTemp))
                .addGroup(md_jPanelTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(md_jPanelTemperaturaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(md_jButtonPrzeliczNaK, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(md_jPanelTemperaturaLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(md_jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(md_jButtonF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(md_jButtonK, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(md_jPanelTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(md_jPanelTemperaturaLayout.createSequentialGroup()
                        .addComponent(md_jLabelWynikTekst1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(md_jLabelWynikTemp, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                    .addComponent(md_jButtonObliczTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        md_jPanelTemperaturaLayout.setVerticalGroup(
            md_jPanelTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(md_jPanelTemperaturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(md_jPanelTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(md_jLabelPodajTemp)
                    .addComponent(md_jButtonC)
                    .addComponent(md_jButtonF)
                    .addComponent(md_jButtonK)
                    .addComponent(md_jButtonObliczTemp)
                    .addComponent(md_jSpinnerTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(md_jPanelTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(md_jLabelPrzeliczNa1)
                    .addComponent(md_jButtonPrzeliczNaC)
                    .addComponent(md_jButtonPrzeliczNaf)
                    .addComponent(md_jButtonPrzeliczNaK)
                    .addComponent(md_jLabelWynikTemp)
                    .addComponent(md_jLabelWynikTekst1))
                .addContainerGap(354, Short.MAX_VALUE))
        );

        md_jTabbedPaneMain.addTab("Temperatura", md_jPanelTemperatura);

        javax.swing.GroupLayout md_jPanelMainLayout = new javax.swing.GroupLayout(md_jPanelMain);
        md_jPanelMain.setLayout(md_jPanelMainLayout);
        md_jPanelMainLayout.setHorizontalGroup(
            md_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(md_jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(md_jTabbedPaneMain)
                .addContainerGap())
        );
        md_jPanelMainLayout.setVerticalGroup(
            md_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(md_jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(md_jTabbedPaneMain)
                .addContainerGap())
        );

        md_jMenuPlik.setText("Plik");

        md_jMenuItemPokazHistorie.setText("Pokaż Historię");
        md_jMenuItemPokazHistorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jMenuItemPokazHistorieActionPerformed(evt);
            }
        });
        md_jMenuPlik.add(md_jMenuItemPokazHistorie);

        md_jMenuItemZamknij.setText("Zamknij");
        md_jMenuPlik.add(md_jMenuItemZamknij);

        md_jMenuBarMain.add(md_jMenuPlik);

        md_jMenuOProgramie.setText("O Programie");

        md_jMenuItemOProgramie.setText("O Programie");
        md_jMenuItemOProgramie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jMenuItemOProgramieActionPerformed(evt);
            }
        });
        md_jMenuOProgramie.add(md_jMenuItemOProgramie);

        md_jMenuBarMain.add(md_jMenuOProgramie);

        setJMenuBar(md_jMenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(md_jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(md_jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    //Zmienne odleglosc: 
    int jednosktkaZKtorejPrzeliczOdleglosc = 0; //1 - cm, 2 - m, 3 - km
    int jednostkaDoKtorejPrzeliczOdleglosc = 0; //1 - cm, 2 - n, 3 - km
    String naJakaJednostkeOdleglosci = "";
    String zJakiejOdleglosciPrzeliczasz = "";
    float odlegloscV;
    float wynikOdleglosc;
    
    //Zmienne temp:
    int jednostkaZktorejPrzeliczTemp = 0; //1 - c, 2 - f, 3 - k;
    int jednostkaDoKtorejPrzeliczTemp = 0; // 1 - c, 2 - f, 3 - k;
    String naJakaJednostkeTemp = "";
    String zJakiejTempPrzeliczasz = "";
    float tempV;
    float wynikTemp;
    
    int co_przeliczasz = 0; //1 - o, 2 = t
    String co_przeliczaszS;
    String jakaOdleglosc;
    String naJakaOdleglosc;
    String jakaTemp;
    String naJakaTemp;
    
    String OczyT;
    String NaOczyT;
    
    File fileSettings = new File("history.txt");
    
    //Kod Odleglosc: 
    private void md_jButtonObliczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jButtonObliczActionPerformed
        co_przeliczasz = 1;
        odlegloscV = (int) md_jSpinnerOdleglosc.getValue();
        System.out.println(""+ odlegloscV);
        
        if (jednosktkaZKtorejPrzeliczOdleglosc == 1 && jednostkaDoKtorejPrzeliczOdleglosc == 1){
            odlegloscV = odlegloscV;
            wynikOdleglosc = odlegloscV;
        }
        if (jednosktkaZKtorejPrzeliczOdleglosc == 1 && jednostkaDoKtorejPrzeliczOdleglosc == 2){
            odlegloscV = odlegloscV / 100;
            wynikOdleglosc = odlegloscV;
            System.out.println(""+wynikOdleglosc);
        }
        else if (jednosktkaZKtorejPrzeliczOdleglosc == 1 && jednostkaDoKtorejPrzeliczOdleglosc == 3){
            odlegloscV = odlegloscV / 100;
            odlegloscV = odlegloscV / 1000;
            wynikOdleglosc = odlegloscV;
            System.out.println(""+wynikOdleglosc);
        }
        else if (jednosktkaZKtorejPrzeliczOdleglosc == 2 && jednostkaDoKtorejPrzeliczOdleglosc == 1){
            odlegloscV = odlegloscV * 100;
            wynikOdleglosc = odlegloscV;
            System.out.println(""+wynikOdleglosc);
        }
        else if (jednosktkaZKtorejPrzeliczOdleglosc == 2 && jednostkaDoKtorejPrzeliczOdleglosc == 2){
            odlegloscV = odlegloscV;
            wynikOdleglosc = odlegloscV;
        }
        else if (jednosktkaZKtorejPrzeliczOdleglosc == 2 && jednostkaDoKtorejPrzeliczOdleglosc == 3){
            odlegloscV = odlegloscV / 1000;
            wynikOdleglosc = odlegloscV;
        }
        else if (jednosktkaZKtorejPrzeliczOdleglosc == 3 && jednostkaDoKtorejPrzeliczOdleglosc == 1){
            odlegloscV = odlegloscV * 1000;
            odlegloscV = odlegloscV * 100;
            wynikOdleglosc = odlegloscV;
            System.out.println(""+wynikOdleglosc);
        }
        else if (jednosktkaZKtorejPrzeliczOdleglosc == 3 && jednostkaDoKtorejPrzeliczOdleglosc == 2){
            odlegloscV = odlegloscV * 1000;
            wynikOdleglosc = odlegloscV;
        }
        else if (jednosktkaZKtorejPrzeliczOdleglosc == 3 && jednostkaDoKtorejPrzeliczOdleglosc == 3){
            odlegloscV = odlegloscV;
            wynikOdleglosc = odlegloscV;
        }
        
        md_jLabelWynik.setText(""+wynikOdleglosc+naJakaJednostkeOdleglosci);
        try {
            saveToFileOdleglosc();
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_md_jButtonObliczActionPerformed

    //Kod temp
    
    //Z której odleglosc
    
    private void md_jButtonCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jButtonCMActionPerformed
        jednosktkaZKtorejPrzeliczOdleglosc = 1;
        zJakiejOdleglosciPrzeliczasz = "cm";
    }//GEN-LAST:event_md_jButtonCMActionPerformed

    private void md_jButtonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jButtonMActionPerformed
        jednosktkaZKtorejPrzeliczOdleglosc = 2;
        zJakiejOdleglosciPrzeliczasz = "m";
    }//GEN-LAST:event_md_jButtonMActionPerformed

    private void md_jButtonKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jButtonKMActionPerformed
        jednosktkaZKtorejPrzeliczOdleglosc = 3;
        zJakiejOdleglosciPrzeliczasz = "km";
    }//GEN-LAST:event_md_jButtonKMActionPerformed

    //Do której odleglosc
    
    private void md_jButtonPrzeliczNaCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jButtonPrzeliczNaCMActionPerformed
        jednostkaDoKtorejPrzeliczOdleglosc = 1;
        naJakaJednostkeOdleglosci = "cm";
    }//GEN-LAST:event_md_jButtonPrzeliczNaCMActionPerformed

    private void md_jButtonPrzeliczNaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jButtonPrzeliczNaMActionPerformed
        jednostkaDoKtorejPrzeliczOdleglosc = 2;
        naJakaJednostkeOdleglosci = "m";
    }//GEN-LAST:event_md_jButtonPrzeliczNaMActionPerformed

    private void md_jButtonPrzeliczNaKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jButtonPrzeliczNaKMActionPerformed
        jednostkaDoKtorejPrzeliczOdleglosc = 3;
        naJakaJednostkeOdleglosci = "km";
    }//GEN-LAST:event_md_jButtonPrzeliczNaKMActionPerformed
    
    //Z Kotrej temp
    
    private void md_jButtonKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jButtonKActionPerformed
        jednostkaZktorejPrzeliczTemp = 3;
        zJakiejTempPrzeliczasz = "k";
    }//GEN-LAST:event_md_jButtonKActionPerformed

    private void md_jButtonPrzeliczNafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jButtonPrzeliczNafActionPerformed
        jednostkaDoKtorejPrzeliczTemp = 2;
        naJakaJednostkeTemp = "F";
    }//GEN-LAST:event_md_jButtonPrzeliczNafActionPerformed

    private void md_jButtonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jButtonFActionPerformed
        jednostkaZktorejPrzeliczTemp = 2;
        zJakiejTempPrzeliczasz = "f";
    }//GEN-LAST:event_md_jButtonFActionPerformed

    private void md_jButtonPrzeliczNaKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jButtonPrzeliczNaKActionPerformed
        jednostkaDoKtorejPrzeliczTemp = 3;
        naJakaJednostkeTemp = "K";
    }//GEN-LAST:event_md_jButtonPrzeliczNaKActionPerformed

    private void md_jButtonObliczTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jButtonObliczTempActionPerformed
        co_przeliczasz = 2;
        tempV = (int) md_jSpinnerTemp.getValue();
        System.out.println(""+tempV);
        
        if (jednostkaZktorejPrzeliczTemp == 1 && jednostkaDoKtorejPrzeliczTemp == 1){
            tempV = tempV;
            wynikTemp = tempV;
        }
        if (jednostkaZktorejPrzeliczTemp == 1 && jednostkaDoKtorejPrzeliczTemp == 2){
            tempV = (float) (tempV * 1.8 + 32);
            wynikTemp = tempV;
        }
        if (jednostkaZktorejPrzeliczTemp == 1 && jednostkaDoKtorejPrzeliczTemp == 3){
            tempV = (float) (tempV + 273.15);
            wynikTemp = tempV;
        }
        if (jednostkaZktorejPrzeliczTemp == 2 && jednostkaDoKtorejPrzeliczTemp == 1){
            tempV = (float) ((tempV - 32)/1.8);
            wynikTemp = tempV;
        }
        if (jednostkaZktorejPrzeliczTemp == 2 && jednostkaDoKtorejPrzeliczTemp == 2){
            tempV = tempV;
            wynikTemp = tempV;
        }
        if (jednostkaZktorejPrzeliczTemp == 2 && jednostkaDoKtorejPrzeliczTemp == 3){
            tempV = (float) ((tempV - 32)/1.8);
            tempV = (float) (tempV + 273.15);
            wynikTemp = tempV;
        } 
        if (jednostkaZktorejPrzeliczTemp == 3 && jednostkaDoKtorejPrzeliczTemp == 1){
            tempV = (float) (tempV - 273.15);
            wynikTemp = tempV;
        }
        if (jednostkaZktorejPrzeliczTemp == 3 && jednostkaDoKtorejPrzeliczTemp == 2){
            tempV = (float) ((tempV * 1.8) - 459.67);
            wynikTemp = tempV;
        }
        if (jednostkaZktorejPrzeliczTemp == 3 && jednostkaDoKtorejPrzeliczTemp == 3){
            tempV = tempV;
            wynikTemp = tempV;
        }
        try {
            saveToFileOdleglosc();
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(""+wynikTemp);
        md_jLabelWynikTemp.setText(""+wynikTemp+naJakaJednostkeTemp);
    }//GEN-LAST:event_md_jButtonObliczTempActionPerformed

    private void md_jButtonPrzeliczNaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jButtonPrzeliczNaCActionPerformed
        jednostkaDoKtorejPrzeliczTemp = 1;
        naJakaJednostkeTemp = "C";
    }//GEN-LAST:event_md_jButtonPrzeliczNaCActionPerformed

    private void md_jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jButtonCActionPerformed
        jednostkaZktorejPrzeliczTemp = 1;
        zJakiejTempPrzeliczasz = "c";
    }//GEN-LAST:event_md_jButtonCActionPerformed

    private void md_jMenuItemPokazHistorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jMenuItemPokazHistorieActionPerformed
        String zapisO;
        String zapisT;
        String helpText;
        char pierwszyZnak;
        char znakZZapisu = 0;
        
        
        helpText = "";
        
        try {
            Scanner in = new Scanner(fileSettings);
            while (in.hasNext()){
                helpText = helpText+in.nextLine()+"\n";
                for (int i = 0; i <= 1; i++){
                    znakZZapisu = helpText.charAt(i);
                }
 
            }
            if (0 == 0){
                JOptionPane.showMessageDialog(null, ""+helpText);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_md_jMenuItemPokazHistorieActionPerformed

    private void md_jMenuItemOProgramieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jMenuItemOProgramieActionPerformed
        JOptionPane.showMessageDialog(null, "Program ma za zadanie przeliczać jednostki temperatury i odległości,\n oraz zapisywanie tych danych do pliku");
    }//GEN-LAST:event_md_jMenuItemOProgramieActionPerformed

    private void saveToFileOdleglosc() throws IOException{
        FileWriter fw = new FileWriter(fileSettings, true);
        BufferedWriter out = new BufferedWriter(fw);
        
        if (co_przeliczasz == 1){
            co_przeliczaszS = "o";
            OczyT = ""+md_jSpinnerOdleglosc.getValue()+zJakiejOdleglosciPrzeliczasz;
            //jakaOdleglosc = ""+md_jSpinnerOdleglosc.getValue()+zJakiejOdleglosciPrzeliczasz;
            NaOczyT = ""+wynikOdleglosc+naJakaJednostkeOdleglosci;
            //naJakaOdleglosc = ""+wynikOdleglosc+naJakaJednostkeOdleglosci;
        }
        
        else if (co_przeliczasz == 2){
            co_przeliczaszS = "t";
            OczyT = ""+md_jSpinnerTemp.getValue()+zJakiejTempPrzeliczasz;
            //jakaTemp = ""+md_jSpinnerTemp.getValue()+zJakiejTempPrzeliczasz;
            //naJakaTemp = ""+wynikTemp+naJakaJednostkeTemp;
            NaOczyT = ""+wynikTemp+naJakaJednostkeTemp;
        }
        
        out.write("\n"+co_przeliczaszS+";"+OczyT+";"+NaOczyT);
        out.close();
    }
    //Do ktorej temp
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton md_jButtonC;
    private javax.swing.JButton md_jButtonCM;
    private javax.swing.JButton md_jButtonF;
    private javax.swing.JButton md_jButtonK;
    private javax.swing.JButton md_jButtonKM;
    private javax.swing.JButton md_jButtonM;
    private javax.swing.JButton md_jButtonOblicz;
    private javax.swing.JButton md_jButtonObliczTemp;
    private javax.swing.JButton md_jButtonPrzeliczNaC;
    private javax.swing.JButton md_jButtonPrzeliczNaCM;
    private javax.swing.JButton md_jButtonPrzeliczNaK;
    private javax.swing.JButton md_jButtonPrzeliczNaKM;
    private javax.swing.JButton md_jButtonPrzeliczNaM;
    private javax.swing.JButton md_jButtonPrzeliczNaf;
    private javax.swing.JLabel md_jLabelPodajOdleglosc;
    private javax.swing.JLabel md_jLabelPodajTemp;
    private javax.swing.JLabel md_jLabelPrzeliczNa;
    private javax.swing.JLabel md_jLabelPrzeliczNa1;
    private javax.swing.JLabel md_jLabelWynik;
    private javax.swing.JLabel md_jLabelWynikTekst;
    private javax.swing.JLabel md_jLabelWynikTekst1;
    private javax.swing.JLabel md_jLabelWynikTemp;
    private javax.swing.JMenuBar md_jMenuBarMain;
    private javax.swing.JMenuItem md_jMenuItemOProgramie;
    private javax.swing.JMenuItem md_jMenuItemPokazHistorie;
    private javax.swing.JMenuItem md_jMenuItemZamknij;
    private javax.swing.JMenu md_jMenuOProgramie;
    private javax.swing.JMenu md_jMenuPlik;
    private javax.swing.JPanel md_jPanelMain;
    private javax.swing.JPanel md_jPanelOdleglosci;
    private javax.swing.JPanel md_jPanelTemperatura;
    private javax.swing.JSpinner md_jSpinnerOdleglosc;
    private javax.swing.JSpinner md_jSpinnerTemp;
    private javax.swing.JTabbedPane md_jTabbedPaneMain;
    // End of variables declaration//GEN-END:variables
}
