/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.dondajewskimichalsprawdzian;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Michał
 */
public class DondajewskiMichalSprawdzian extends javax.swing.JFrame {

    /**
     * Creates new form DondajewskiMichalSprawdzian
     */
    public DondajewskiMichalSprawdzian() {
        initComponents();
        addKeyListernerTo_md_jTextFieldZnakModelu();
        addKeyListtenerTo_md_jTextFieldNumerPartii();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        md_jPanelMain = new javax.swing.JPanel();
        md_jLabelNumerSeryjny = new javax.swing.JLabel();
        md_jLabelZnakModelu = new javax.swing.JLabel();
        md_jTextFieldZnakModelu = new javax.swing.JTextField();
        md_jLabelNumerPartii = new javax.swing.JLabel();
        md_jTextFieldNumerPartii = new javax.swing.JTextField();
        md_jButtonZapisz = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        md_jMenuPlik = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        md_jPanelMain.setBackground(new java.awt.Color(204, 255, 204));

        md_jLabelNumerSeryjny.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        md_jLabelNumerSeryjny.setText("Numer seryjny urządzenia: ");

        md_jLabelZnakModelu.setText("Znak modelu");

        md_jTextFieldZnakModelu.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        md_jLabelNumerPartii.setText("Numer partii");

        md_jTextFieldNumerPartii.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        md_jButtonZapisz.setText("ZAPIS");
        md_jButtonZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jButtonZapiszActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout md_jPanelMainLayout = new javax.swing.GroupLayout(md_jPanelMain);
        md_jPanelMain.setLayout(md_jPanelMainLayout);
        md_jPanelMainLayout.setHorizontalGroup(
            md_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(md_jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(md_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(md_jLabelNumerSeryjny)
                    .addGroup(md_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(md_jButtonZapisz)
                        .addGroup(md_jPanelMainLayout.createSequentialGroup()
                            .addGroup(md_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(md_jTextFieldZnakModelu, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(md_jLabelZnakModelu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(180, 180, 180)
                            .addGroup(md_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(md_jLabelNumerPartii)
                                .addComponent(md_jTextFieldNumerPartii, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        md_jPanelMainLayout.setVerticalGroup(
            md_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(md_jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(md_jLabelNumerSeryjny)
                .addGap(18, 18, 18)
                .addGroup(md_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(md_jLabelZnakModelu)
                    .addComponent(md_jLabelNumerPartii))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(md_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(md_jTextFieldZnakModelu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(md_jTextFieldNumerPartii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(md_jButtonZapisz)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        md_jMenuPlik.setText("Plik");
        jMenuBar1.add(md_jMenuPlik);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(md_jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(md_jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    String model;
    String partia;
    String zapis;
    
    private void md_jButtonZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jButtonZapiszActionPerformed
        FileWriter fw = null;
        try {
            model = md_jTextFieldZnakModelu.getText();
            partia = md_jTextFieldNumerPartii.getText();
            zapis = ""+partia+" - "+model;
            File f = new File("dondajewski_michal.txt");
            fw = new FileWriter(f);
            fw.write(zapis);
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(DondajewskiMichalSprawdzian.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        
    }//GEN-LAST:event_md_jButtonZapiszActionPerformed
    
    private void addKeyListernerTo_md_jTextFieldZnakModelu(){
        md_jTextFieldZnakModelu.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                char znak = e.getKeyChar();
                int kod = (int) znak;
                
                if (kod >= 97 && kod <= 199 || znak == KeyEvent.VK_BACK_SPACE){
                    md_jTextFieldZnakModelu.setEditable(true);
                }else{
                    md_jTextFieldZnakModelu.setEditable(false);
                }
            }

            @Override
            public void keyPressed(KeyEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void keyReleased(KeyEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }
    
    private void addKeyListtenerTo_md_jTextFieldNumerPartii(){
        md_jTextFieldNumerPartii.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                char znak = e.getKeyChar();
                int kod = (int) znak;
                if (znak >= '0' && znak <= '9' || znak == '.' || znak == KeyEvent.VK_BACK_SPACE){
                    //Wpisany dobry znak
                    md_jTextFieldNumerPartii.setEditable(true);   
                }
                else {
                    //Wpisany zły znak
                    md_jTextFieldNumerPartii.setEditable(false);
                }                        
            }

            @Override
            public void keyPressed(KeyEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void keyReleased(KeyEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DondajewskiMichalSprawdzian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DondajewskiMichalSprawdzian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DondajewskiMichalSprawdzian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DondajewskiMichalSprawdzian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DondajewskiMichalSprawdzian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton md_jButtonZapisz;
    private javax.swing.JLabel md_jLabelNumerPartii;
    private javax.swing.JLabel md_jLabelNumerSeryjny;
    private javax.swing.JLabel md_jLabelZnakModelu;
    private javax.swing.JMenu md_jMenuPlik;
    private javax.swing.JPanel md_jPanelMain;
    private javax.swing.JTextField md_jTextFieldNumerPartii;
    private javax.swing.JTextField md_jTextFieldZnakModelu;
    // End of variables declaration//GEN-END:variables
}
